polydog:
  
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 25

  # leg1 Controllers ------------------------------------------------------------ 
  shoulder1:
      type: effort_controllers/JointPositionController
      joint: shoulder1
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  hip1:
      type: effort_controllers/JointPositionController
      joint: hip1
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  knee1:
      type: effort_controllers/JointPositionController
      joint: knee1
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # leg2 Controllers ------------------------------------------------------------ 
  shoulder2:
      type: effort_controllers/JointPositionController
      joint: shoulder2
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  hip2:
      type: effort_controllers/JointPositionController
      joint: hip2
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  knee2:
      type: effort_controllers/JointPositionController
      joint: knee2
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # leg3 Controllers ------------------------------------------------------------ 
  shoulder3:
      type: effort_controllers/JointPositionController
      joint: shoulder3
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  hip3:
      type: effort_controllers/JointPositionController
      joint: hip3
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  knee3:
      type: effort_controllers/JointPositionController
      joint: knee3
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # leg4 Controllers ------------------------------------------------------------     
  shoulder4:
      type: effort_controllers/JointPositionController
      joint: shoulder4
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  hip4:
      type: effort_controllers/JointPositionController
      joint: hip4
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  knee4:
      type: effort_controllers/JointPositionController
      joint: knee4
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
